<!-- nav.inc -->
<nav class="nav-bar">
  <button class="nav-btn" onclick="location.href='../project2/index.php'">Home</button>
  <button class="nav-btn" onclick="location.href='../project2/jobs.php'">Jobs</button>
  <button class="nav-btn" onclick="location.href='../project2/apply.php'">Apply</button>
  <button class="nav-btn" onclick="location.href='../project2/manage.php'">Manage</button>
  <button class="nav-btn" onclick="location.href='../project2/enhancements.php'">Enhancements</button>
  <button class="nav-btn" onclick="location.href='../project2/about.php'">About</button>
</nav>
