
<!-- footer.inc -->
<footer class="footer">

  <div class="footer-content">
    

    <div class="footer-column">
      <h3>Site Map</h3>
      <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="manage.php">Manage</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="about.php">About</a></li>
      </ul>
    </div>


    <div class="footer-column">
      <h3>Legal</h3>
      <ul>
        <li><a target="_blank" href="https://www.w3.org/WAI/">Accessibility</a></li>
        <li><a target="_blank" href="https://www.freeprivacypolicy.com/live/292d5595-d5c5-45e2-86a0-520d0141f5de">Cookie Policy</a></li>
        <li><a target="_blank" href="https://swintechcos10026.github.io/SwinTech-GroupProject/extra-files-for-links/SwinTch-website-disclaimer.pdf">Disclaimer</a></li>
        <li><a target="_blank" href="https://swintechcos10026.github.io/SwinTech-GroupProject/extra-files-for-links/Placeholder Privacy Policy.pdf">Privacy Policy</a></li>
        <li><a target="_blank" href="https://swintechcos10026.github.io/SwinTech-GroupProject/extra-files-for-links/Terms_and_Services_Agreement.pdf">Terms & Services</a></li>
        
      </ul>
    </div>


    <div class="footer-column">
      <h3>Connect</h3>
      <div class="footer-icons">
        <a href="https://www.facebook.com/" target="_blank"><img src="styles/images/facebook.svg" alt="Facebook" /></a>
        <a href="https://www.linkedin.com/" target="_blank"><img src="styles/images/linkedin.svg" alt="LinkedIn" /></a>
        <a href="https://www.x.com/" target="_blank"><img src="styles/images/x.svg" alt="x" /></a>
        <a href="https://swintech1234.atlassian.net/jira/software/projects/SWIN/summary" target="_blank"><img src="styles/images/jira.svg" alt="Jira" /></a>
        <a href="https://github.com/SwinTechCOS10026/SwinTech-GroupProject.git" target="_blank"><img src="styles/images/github.svg" alt="GitHub" /></a>
      </div>
    </div>

  </div>

  <div class="footer-bottom">
    <p>&copy; 2025 SwinTech – All Rights Reserved</p>
  </div>
</footer>
