<!-- header.inc -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="SwinTech is a project team building modern web solutions.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SwinTech</title>
        <link href="https://fonts.googleapis.com" rel="preconnect">
        <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect">
        <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@100..900&amp;family=Onest:wght@100..900&amp;display=swap"
            rel="stylesheet">
        <link rel="icon" href="images/icon.png" type="image/png">
        <link rel="stylesheet" href="styles/styles.css">
    </head>
<body class="<?php echo isset($pageClass) ? $pageClass : ''; ?>">
  <header class="header">
    <div class="logo">
      <img src="images/logo.png" alt="SwinTech Logo">
    </div>
</header>